[package]
name = "robotnix-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.32", features = ["derive"] }
atomic-write-file = "0.2.3"
